### ISSUE TITLE
The total score for the CodeWars task was calculated incorrectly

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/karate#28]
Example:
https://www.codewars.com/users/VeronikaShneidzer

All tasks were solved but total score is just 46.

**Comment by ragexe** [comment]
https://www.codewars.com/users/justwokeup/

All tasks were solved but total score is just 0.

**Comment by avernikoz** [comment]
https://www.codewars.com/users/avernikoz/

All tasks were solved but total score is just 0.

**Comment by prazuvalov** [comment]
https://www.codewars.com/users/prazuvalov
Total score is 0

**Comment by mashagrand4** [comment]
https://www.codewars.com/users/mashagrand4
Much tasks were solved but total score is just 0.

**Comment by AlekseyMinsk** [comment]
https://www.codewars.com/users/Eminem

All tasks were solved but total score is just 0.

**Comment by Tatsiya** [comment]
All the tasks were solved but total score is just 0.

**Comment by arsafab** [comment]
https://www.codewars.com/users/arsafab
All tasks were solved but total score is just 0.

**Comment by AtabayArniyazov** [comment]
https://www.codewars.com/users/Atabay%20Arniyazov
total score is just 0.

**Comment by Tatsiya** [comment]
https://www.codewars.com/users/Tatsiya
All the tasks were solved but total score is  0.

**Comment by manuminsk** [comment]
https://www.codewars.com/users/manuminsk
All the tasks were solved but total score is 0.

**Comment by marinovich** [comment]
https://www.codewars.com/users/marinovich
All tasks were solved but total score is 97

**Comment by nuam** [comment]
https://www.codewars.com/users/nuam
All tasks were solved but total score is just 0.

**Comment by Atzkdeff** [comment]
https://www.codewars.com/users/bende_r
All the tasks +1additional were solved but total score is just 0.

**Comment by StepanPG** [comment]
https://www.codewars.com/users/StepanPG
Total score is just 0.

**Comment by VladislavBaranov** [comment]
https://www.codewars.com/users/VladislavBaranov
Total score is 0.

**Comment by Globalbobone** [comment]
https://www.codewars.com/users/Globalbobone
total 37

**Comment by BezakDenis** [comment]
https://www.codewars.com/users/BloodofDen

All tasks were solved but total score is just 85.

**Comment by Globalbobone** [comment]
https://www.codewars.com/users/Globalbobone
total 37

**Comment by pasyukevich** [comment]
https://www.codewars.com/users/pasyukevich
All tasks were solved but total score is 64.

**Comment by meller96** [comment]
https://www.codewars.com/users/meller777
Total score is 0

**Comment by forkollaider** [comment]
First fix. will help students who got 97 points on first iterations

**Comment by igor-provotorov** [comment]
https://www.codewars.com/users/igor-provotorov
Total score is 0

**Comment by RudikAleksandr** [comment]
https://www.codewars.com/users/RudikAleksandr
All tasks were solved but total score is just 0.

**Comment by KirillKirill** [comment]
https://www.codewars.com/users/Kirill%20Bochkarev
Tasks were solved, but total score is 0

**Comment by gleb7raul** [comment]
https://www.codewars.com/users/gleb7raul?
Tasks were sloved,but total score is 0

**Comment by lindenii** [comment]
https://www.codewars.com/users/lindenii
All tasks were solved but total score is 38.

**Comment by dzianisbohush** [comment]
https://www.codewars.com/users/dzianisbohush
29/32 katas were solved and total score 69(

**Comment by eugene-fedurkin** [comment]
32/32(+ 3/4 optional) katas were solved and total score 88.

**Comment by sulemanof** [comment]
https://www.codewars.com/users/sulemanof
All tasks were solved +3 optional but total score is just 92.

**Comment by Interstlr** [comment]
29/32 tasks were solved and total score is 83. should it be higher if avg. value of one task is 3.125?

**Comment by anastminsk** [comment]
All tasks were solved +1 optional, total score is 95

**Comment by bilysha** [comment]
https://github.com/bilysha
32/32 tasks were solved, +1 optional, but score 10

**Comment by ArlinskiEV** [comment]
https://www.codewars.com/users/ArlinskiEV

All tasks were solved but total score is just 98.

**Comment by KravchenkoDenis1** [comment]
https://www.codewars.com/users/Shank
All tasks were solved but total score is just 95. 
(32/32) 0 optional

**Comment by Saroko-dnd** [comment]
https://www.codewars.com/users/Igor-Saroko

All tasks were solved, + 4 optional, but total score is 0.

**Comment by sajdre** [comment]
https://www.codewars.com/users/sajdre

All tasks were solved (+4 optional) but total score is 65.

**Comment by katrin2404** [comment]
https://www.codewars.com/users/Katrin2404

All tasks were solved and 3 optional but total score is just 33.

**Comment by viktorsamkevich** [comment]
https://www.codewars.com/users/viktorsamkevich

All tasks were solved but total score is just 98.

**Comment by Shest28** [comment]
https://www.codewars.com/users/shest28
All tasks were solved (+optional) but total score is just 63.

**Comment by MikalaiSkru** [comment]
https://www.codewars.com/users/MikalaiSkru
All tasks were solved but total score is 0.

**Comment by Supersmf** [comment]
https://www.codewars.com/users/Supersmf
All tasks were solved +2 optional, but total score is just 58

**Comment by stvader** [comment]
All tasks were solved but total score is just 79.

**Comment by alesmik** [comment]
All 32 of required katas and all of 4 optional ones are solved. The score is 97.

**Comment by OlgaMardvilko** [comment]
https://www.codewars.com/users/OlgaMardvilko
25/32 katas were solved and total score 57

**Comment by TrLuda** [comment]
https://www.codewars.com/users/TrLuda
All tasks were solved but total score is 0.

**Comment by RomanYablonski** [comment]
https://www.codewars.com/users/Roman-Yablonski
All 32 of required katas and 2 of 4 optional katas are solved. The score is 98.

**Comment by kirillpanov** [comment]
https://www.codewars.com/users/kirillpanov
All 32 mandatory tasks were solved + 1 optional but total score is just 82.

**Comment by PolinaBobrovnik** [comment]
https://www.codewars.com/users/polinabobrovnik
All tasks + 2 optional were solved but total score is just 52.

**Comment by cruecer** [comment]
total score is 0

**Comment by chelovekdrakon** [comment]
https://www.codewars.com/users/chelovekdrakon
32/32 were solved, but the score is 87

**Comment by Trinnitty** [comment]
https://www.codewars.com/users/Trinnitty
31/32 were solved, but the score is 70.

**Comment by GoncharukYa** [comment]
https://www.codewars.com/users/goyr
32/32
score is 82

**Comment by an-art** [comment]
https://www.codewars.com/users/an-art
All tasks + 2 optional were solved but total score is just 88.

**Comment by KVtofan** [comment]
https://www.codewars.com/users/KVtofan/completed

**Comment by hlazunova-katya** [comment]
https://www.codewars.com/users/mistress
All  tasks except the 4kyu kata were solved, and the total score was supposed to be 90, but it is 86.

**Comment by Morfinbrood** [comment]
28/32 tasks were solved and total score is 80. should it be 82.
https://www.codewars.com/users/Morfinbrood
Not solved next tasks: 
function-composition-1  6kuy  -4 points
i-spy                                5kuy   -5 points
new-with-apply               6kuy  -4 points
replicate-new                  5kuy   -5 points

**Comment by Tatsiya** [comment]
https://www.codewars.com/users/Tatsiya
All tasks were solved but total score is just 96

**Comment by maksimyakush** [comment]
https://www.codewars.com/users/maksimyakush
Around 90% of mandatory and 2 optional tasks were solved but total score is 0.

**Comment by RudikAleksandr** [comment]
https://www.codewars.com/users/RudikAleksandr
All tasks were solved and +4 optional, but total score is just 98.

**Comment by DaryaBobko** [comment]
https://www.codewars.com/users/DaryaBobko
There is no estimate in Score

**Comment by Slegan** [comment]
https://www.codewars.com/users/Slegan
All tasks were solved but total score is just 97.

**Comment by Vladlan** [comment]
https://www.codewars.com/users/Vladlan
All tasks were solved and also one optional (http://www.codewars.com/kata/lazy-evaluation) but total score  98.

**Comment by AmsterGet** [comment]
All tasks were solved and also one optional but total score 98.
https://www.codewars.com/users/AmsterGet

**Comment by DenisSoft** [comment]
https://www.codewars.com/users/DenisSoft
All tasks were solved but total score is just 0.

**Comment by evgesha0411** [comment]
https://www.codewars.com/users/evgesha0411
A couple of points migth got lost

**Comment by galievsky** [comment]
https://www.codewars.com/users/Alex5126
All tasks were solved but total score is just 82.

**Comment by viachaslau-latushkin** [comment]
https://www.codewars.com/users/viachaslau-latushkin
Solved all, except 2 optional, but 88. May be it is normally...

**Comment by AngelinaPanteley** [comment]
https://www.codewars.com/users/AngelinaPanteley
All tasks and 1 optional (3kyu)  were solved but total score is just 98.

**Comment by bilysha** [comment]
https://www.codewars.com/users/bilysha
32/32 tasks were solved, +1 optional, but score 10

**Comment by Globalbobone** [comment]
https://github.com/Globalbobone
All tasks were solved but total score is just 75.

**Comment by Natallia-Hutovich** [comment]
https://www.codewars.com/users/Natallia-Hutovich 
32/32 tasks were solved but total score is just 96.

**Comment by marinovich** [comment]
All tasks were solved +all optional, but total score is 87.
A few days ago was 97))

**Comment by SergeyPismennyi** [comment]
All tasks were solved, except "base-conversion". It was also solved "can-you-get-the-loop". But score is 76.
https://www.codewars.com/users/Shax

**Comment by Atzkdeff** [comment]
https://www.codewars.com/users/bende_r
All the tasks +1additional were solved but total score is just 98.
I checked my completed task and total score should be 105

**Comment by Tatsiya** [comment]
https://www.codewars.com/users/Tatsiya
All the tasks were solved but total score is just 97.
Total score should be 100.

**Comment by bilysha** [comment]
https://www.codewars.com/users/bilysha
32/32 tasks were solved_(100), +1 optional(3 kyu)_(15), total score should be 115 instead of 97

**Comment by eugene-fedurkin** [comment]
https://www.codewars.com/users/Jene
All the tasks +3additional were solved but total score is just 97.
Total score should be 125

**Comment by infiniti008** [comment]
All tasks were solved but total score is 67.
A few days ago was 97!!!
https://www.codewars.com/users/infiniti008/completed

**Comment by SLTS87** [comment]
https://www.codewars.com/users/SLTS87
3 of 32 tasks were not solved (№19 - 5 points, №22 - 4 points and №23 - 5 points). Total score should be 86.

**Comment by VladislavBaranov** [comment]
https://www.codewars.com/users/VladislavBaranov
Total score is 0.

**Comment by alexfis** [comment]
[https://www.codewars.com/users/ltcolumbo](url)
Total score is 0.

**Comment by EmptyChild** [comment]
https://www.codewars.com/users/EmptyChild42
All obligatory tasks were solved but total score is 0 (yesterday everything was ok)

**Comment by kirillpanov** [comment]
https://www.codewars.com/users/kirillpanov
All 32 mandatory tasks were solved + 1 optional but total score is 0.

**Comment by Vladimir2430** [comment]
https://www.codewars.com/users/Vladimir2430
All obligatory tasks were solved but total score is 0 (yesterday everything was ok)

**Comment by VladislavBaranov** [comment]
https://www.codewars.com/users/VladislavBaranov
Total score is 0. in score my name Uladzislau Baranau

**Comment by arsafab** [comment]
https://www.codewars.com/users/arsafab
All tasks + 3 optional were solved but total score is still 0.

**Comment by lerstel** [comment]
https://www.codewars.com/users/lerstel
Total score is 0.

**Comment by forkollaider** [comment]
@lerstel Please check your account presence in github to codewars mapping
https://docs.google.com/spreadsheets/d/1472j2my-gmGNUoatrdgifTpucSsivrPQEXSZdQgzwIo/edit#gid=0

**Comment by forkollaider** [comment]
Dear students! All scores were updated, please check them. Before adding new comment to this issue,please check that your github and codewars account are present in mapping dock.
If you have more than 200 issue solved the issue might still accrue. We are doing all possible to resolve this issue

**Comment by TrLuda** [comment]
Instead of my profile, I have e-mail address. How can I fix it?

**Comment by Saroko-dnd** [comment]
https://www.codewars.com/users/Igor-Saroko

All tasks were solved, (including all optional), but total score is just 110.

**Comment by arsafab** [comment]
https://www.codewars.com/users/arsafab
All tasks + 3 optional were solved but total score is still 0.

**Comment by forkollaider** [comment]
@arsafab please check my comment above. u have 392 solved katas

**Comment by forkollaider** [comment]
@TrLuda please provide your accond name here. i will update mapping document

**Comment by forkollaider** [comment]
@Saroko-dnd solved for you

**Comment by Heat98** [comment]
There is still no mark for the codewars.
Dzmitry Kovalenko in score.
https://www.codewars.com/users/Heat/completed

**Comment by TrLuda** [comment]
https://www.codewars.com/users/TrLuda
My name TrLuda for everything

**Comment by bilysha** [comment]
https://www.codewars.com/users/bilysha
All tasks were solved, +1 optional(3 kyu), but total score is 100

**Comment by forkollaider** [comment]
@TrLuda updated

**Comment by forkollaider** [comment]
@bilysha updated

**Comment by forkollaider** [comment]
Please notice that empty result and 0 are different scores!

**Comment by stanislawa** [comment]
Total score is 0.
https://www.codewars.com/users/slw

**Comment by lastlion** [comment]
https://www.codewars.com/users/lastlion
I have 50 points by my calculations, but total score is just 44.

**Comment by forkollaider** [comment]
@stanislawa @lastlion will be recounted on next iteration

**Comment by lerstel** [comment]
Yeah, i checked. All my usernames are correct but still have 0 for
codewards in Score

2017-11-24 13:27 GMT+03:00 Tsikhan Shcharbakou <notifications@github.com>:

**Comment by yoshirolas** [comment]
https://www.codewars.com/users/yoshirolas
25/32 tasks were solved but total score is 0

**Comment by VladislavBaranov** [comment]
https://www.codewars.com/users/VladislavBaranov
Total score is 0. in score my name Uladzislau Baranau

**Comment by KirillKirill** [comment]
Total score is still 0. Kirill Bochkarev

**Comment by VladislavBaranov** [comment]
https://www.codewars.com/users/VladislavBaranov
Total score is тnothing. in score my name Uladzislau Baranau

**Comment by lerstel** [comment]
Total codewars score is still 0. Molochko Egor(lerstel)

Отправлено с iPhone

**Comment by VladislavBaranov** [comment]
https://www.codewars.com/users/VladislavBaranov
Total score is nothing. in score my name Uladzislau Baranau
Help!!!!
